// pin configs
#define MOTOR1PWM D5
#define BIPOLAR1 D4 
#define DIRECTION1 PB_12

#define USE_RC_MODE

#define MOTOR2PWM D3
#define BIPOLAR2 D7
#define DIRECTION2 PC_4

#define ENABLE_PIN D9

#define BLE_RX D10
#define BLE_TX D2
#define BLE_PINS_TUPLE BLE_RX, BLE_TX, BLE_BAUD // ignore

#define ENCODER1_CHA PC_3
#define ENCODER1_CHB PH_0
#define ENCODER2_CHA PC_2
#define ENCODER2_CHB PH_1

#define LINE_SENSOR_1_PIN A1
#define LINE_SENSOR_2_PIN A4
#define LINE_SENSOR_3_PIN A5
#define LINE_SENSOR_4_PIN A3

#define SENSOR_BANK_1_PIN PC_6
#define SENSOR_BANK_2_PIN PC_8

// Settings

#define Frequency 25000.0
#define Period 1.0/Frequency

#define ENCODER_MEASURE_RATE 0.005
#define PID_ENCODER_FREQ 0.01
#define PID_NAVIGATION_FREQ 0.01
#define DATA_MEASURE_FREQ 0.05
#define BLE_POLL_FREQ 0.01
#define LINESENSOR_POLL_RATE 0.01

#define BLE_BAUD 9600

#define ACCELERATION_RATE_PER_TICK 0.01

// CALLBACK SIGNALS FOR STANDARDISING THINGS
#define TOGGLE_LED_SIGNAL 99
#define TOGGLE_ENABLE_SIGNAL 95
#define TOGGLE_INTERPOLATION 92

#define CHANGE_VALUE_SIGNAL 50
#define CHANGE_VALUE_QUICK_SIGNAL 51
#define CHANGE_VALUE_BEING_CHANGED_SIGNAL 55
#define SET_SPEED_QUICK 59

#define ROTATE_180_SIGNAL 77
#define TOGGLE_STOP_COND_SIGNAL 88
#define TOGGLE_PRINT_ENCODERS_SIGNAL 22
#define TOGGLE_PRINT_SERIAL_SIGNAL 23

#define SET_MOTOR1_SPEED_SIGNAL 40
#define SET_MOTOR2_SPEED_SIGNAL 50

#define ENABLE_TICKERS_SIGNAL 33
#define DISABLE_TICKERS_SIGNAL 34

#define TOGGLE_SENSOR_USAGE_SIGNAL 35

#define ENABLE_MOTORS_SIGNAL 36
#define DISABLE_MOTORS_SIGNAL 37

#define FORWARD_SIGNAL 61
#define BACKWARD_SIGNAL 62
#define LEFT_SIGNAL 63
#define RIGHT_SIGNAL 64

// Sensor Navigation Tolerances
#define BANK_1_STOP_CONDITION 0.3